redirects:
- from: build_pipeline_bundle.html
  to: build/index.html
- from: build_pipeline_bundle_steps.html
  to: build/bundle-steps.html
- from: build_pipeline_bundle_structure.html
  to: build/bundle-structure.html
- from: dataflow_spec_ref_cdc.html
  to: build/spec-reference/cdc.html
- from: dataflow_spec_ref_data_quality.html
  to: build/spec-reference/data-quality.html
- from: dataflow_spec_ref_main_flows.html
  to: build/spec-reference/flows.html
- from: dataflow_spec_ref_main_materialized_views.html
  to: build/spec-reference/materialized-views.html
- from: dataflow_spec_ref_main_standard.html
  to: build/spec-reference/standard.html
- from: dataflow_spec_ref_source_details.html
  to: build/spec-reference/source-details.html
- from: dataflow_spec_ref_table_migration.html
  to: build/spec-reference/table-migration.html
- from: dataflow_spec_ref_target_details.html
  to: build/spec-reference/target-details.html
- from: dataflow_spec_reference.html
  to: build/spec-reference/index.html
- from: patterns.html
  to: build/patterns/index.html
- from: patterns_streaming_basic_1_1.html
  to: build/patterns/basic-1-1.html
- from: patterns_streaming_cdc_stream_from_snapshot.html
  to: build/patterns/cdc-stream-from-snapshot.html
- from: patterns_streaming_flow_groups.html
  to: build/patterns/flow-groups.html
- from: patterns_streaming_multi_source_streaming.html
  to: build/patterns/multi-source-streaming.html
- from: patterns_streaming_stream_static_basic.html
  to: build/patterns/stream-static-basic.html
- from: patterns_streaming_stream_static_streaming_dwh.html
  to: build/patterns/stream-static-streaming-dwh.html
- from: splitting_dataflow_spec.html
  to: build/spec-reference/splitting-dataflow-spec.html
